/**
 Свои исключения

 @since 21.01.2019 01 2019 (23:15) */
package ru.vachok.networker.errorexceptions;